Repository ngaly277/zoo-management, pull requests merged in 2023-04, with the labels that each got.

#20 Done TicketManager
  ZooManagement/pom.xml
  ZooManagement/src/main/java/fa/intern/mock/controller/AdminTicketAgeController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/AdminTicketController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/AdminTicketTypeController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/TicketController.java
  ZooManagement/src/main/java/fa/intern/mock/dao/TicketAgeDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/TicketDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/TicketTypeDAO.java
  ZooManagement/src/main/java/fa/intern/mock/service/TicketAgeService.java
  ZooManagement/src/main/java/fa/intern/mock/service/TicketService.java
  ZooManagement/src/main/java/fa/intern/mock/service/TicketTypeService.java
  ZooManagement/src/main/webapp/WEB-INF/springmvc-servlet.xml
  ZooManagement/src/main/webapp/admin/navbar.jsp
  ZooManagement/src/main/webapp/admin/ticketAgeManager.jsp
  ZooManagement/src/main/webapp/admin/ticketAgeManagerEdit.jsp
  ZooManagement/src/main/webapp/admin/ticketManager.jsp
  ZooManagement/src/main/webapp/admin/ticketManagerEdit.jsp
  ZooManagement/src/main/webapp/admin/ticketTypeManager.jsp
  ZooManagement/src/main/webapp/admin/ticketTypeManagerEdit.jsp
  ZooManagement/src/main/webapp/resources/css/style-page-admin.css
  ZooManagement/src/main/webapp/resources/js/admin-ticket-manager.js
Labels: enhancement

#21 Feature/removestaff
  .gitignore
  Servers/.project
  Servers/.settings/org.eclipse.core.resources.prefs
  Servers/.settings/org.eclipse.wst.server.core.prefs
  Servers/Tomcat v10.1 Server at localhost-config/catalina.policy
  Servers/Tomcat v10.1 Server at localhost-config/catalina.properties
  Servers/Tomcat v10.1 Server at localhost-config/context.xml
  Servers/Tomcat v10.1 Server at localhost-config/server.xml
  Servers/Tomcat v10.1 Server at localhost-config/tomcat-users.xml
  Servers/Tomcat v10.1 Server at localhost-config/web.xml
  ZooManagement/.classpath
  ZooManagement/src/main/java/fa/intern/mock/bean/Account.java
  ZooManagement/src/main/java/fa/intern/mock/bean/Contracts.java
  ZooManagement/src/main/java/fa/intern/mock/bean/Staff.java
  ZooManagement/src/main/java/fa/intern/mock/bean/StaffType.java
  ZooManagement/src/main/java/fa/intern/mock/controller/AccountController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/ContractController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/StaffListController.java
  ZooManagement/src/main/java/fa/intern/mock/dao/AccountDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/ContractDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/CustomerDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/StaffDAO.java
  ZooManagement/src/main/java/fa/intern/mock/dao/TicketDAO.java
  ZooManagement/src/main/java/fa/intern/mock/service/AccountService.java
  ZooManagement/src/main/java/fa/intern/mock/service/ContractService.java
  ZooManagement/src/main/java/fa/intern/mock/service/StaffService.java
  ZooManagement/src/main/webapp/WEB-INF/springmvc-servlet.xml
  ZooManagement/src/main/webapp/WEB-INF/web.xml
  ZooManagement/src/main/webapp/admin/Login.jsp
  ZooManagement/src/main/webapp/admin/Staff.jsp
  ZooManagement/src/main/webapp/admin/StaffCreate.jsp
  ZooManagement/src/main/webapp/admin/StaffUpdate.jsp
Labels: enhancement

#23 Change .classpath to prevent issue
  ZooManagement/.classpath
  ZooManagement/.settings/org.eclipse.wst.common.component
Labels: bug

#29 Fix tomcat error when launching
  ZooManagement/.classpath
  ZooManagement/.settings/org.eclipse.core.resources.prefs
  ZooManagement/.settings/org.eclipse.jdt.apt.core.prefs
  ZooManagement/.settings/org.eclipse.jdt.core.prefs
  ZooManagement/.vscode/settings.json
  ZooManagement/pom.xml
  ZooManagement/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar
  ZooManagement/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-api-2.0.0.jar
  ZooManagement/src/main/webapp/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar
Labels: bug

#33 Update feature
  ZooManagement/.classpath
  ZooManagement/src/main/java/fa/intern/mock/controller/AnimalController.java
  ZooManagement/src/main/java/fa/intern/mock/controller/CageController.java
  ZooManagement/src/main/webapp/WEB-INF/springmvc-servlet.xml
  ZooManagement/src/main/webapp/admin/cage.jsp
  ZooManagement/src/main/webapp/admin/editAnimal.jsp
Labels: documentation, enhancement
